export const CardDate = [
  {
    id: 1,
    image: `python.jpg`,
    title: " Learn Python: The Complete Python Programming Course",
    auther: "Avinash Jain, The Codex",
    starRate: 2.4,
    students: 1.247,
    price: 679.99,
    category: "python",
  },
  {
    id: 2,
    image: "python2.jpg",
    title: " Learn Python: The Complete Python Programming Course",
    auther: "Avinash Jain, The Codex",
    starRate: 1.4,
    students: 1.247,
    price: 679.99,
    category: "python",
  },
  {
    id: 3,
    image: "python3.jpg",
    title: " Learn Python: The Complete Python Programming Course",
    auther: "Avinash Jain, The Codex",
    starRate: 4.4,
    students: 1.247,
    price: 679.99,
    category: "python",
  },
  {
    id: 4,
    image: "python4.jpg",
    title: " Learn Python: The Complete Python Programming Course",
    auther: "Avinash Jain, The Codex",
    starRate: 4.4,
    students: 1.247,
    price: 679.99,
    category: "python",
  },
  {
    id: 5,
    image: "python4.jpg",
    title: " Learn Python: The Complete Python Programming Course",
    auther: "Avinash Jain, The Codex",
    starRate: 4.4,
    students: 1.247,
    price: 679.99,
    category: "python",
  },
];
